// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.protobuf.jbean;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protobuf.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>string birthday = 3;</code>
     */
    java.lang.String getBirthday();
    /**
     * <code>string birthday = 3;</code>
     */
    com.google.protobuf.ByteString
        getBirthdayBytes();

    /**
     * <code>bool man = 4;</code>
     */
    boolean getMan();

    /**
     * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
     */
    java.util.List<com.protobuf.jbean.PersonProto.Person.PhotoNumber> 
        getPhoneList();
    /**
     * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
     */
    com.protobuf.jbean.PersonProto.Person.PhotoNumber getPhone(int index);
    /**
     * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
     */
    int getPhoneCount();
    /**
     * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
     */
    java.util.List<? extends com.protobuf.jbean.PersonProto.Person.PhotoNumberOrBuilder> 
        getPhoneOrBuilderList();
    /**
     * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
     */
    com.protobuf.jbean.PersonProto.Person.PhotoNumberOrBuilder getPhoneOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.protobuf.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protobuf.Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      age_ = 0;
      birthday_ = "";
      man_ = false;
      phone_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              birthday_ = s;
              break;
            }
            case 32: {

              man_ = input.readBool();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                phone_ = new java.util.ArrayList<com.protobuf.jbean.PersonProto.Person.PhotoNumber>();
                mutable_bitField0_ |= 0x00000010;
              }
              phone_.add(
                  input.readMessage(com.protobuf.jbean.PersonProto.Person.PhotoNumber.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          phone_ = java.util.Collections.unmodifiableList(phone_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.jbean.PersonProto.internal_static_com_protobuf_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.jbean.PersonProto.internal_static_com_protobuf_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.jbean.PersonProto.Person.class, com.protobuf.jbean.PersonProto.Person.Builder.class);
    }

    /**
     * Protobuf enum {@code com.protobuf.Person.PhotoType}
     */
    public enum PhotoType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORD = 2;</code>
       */
      WORD(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORD = 2;</code>
       */
      public static final int WORD_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhotoType valueOf(int value) {
        return forNumber(value);
      }

      public static PhotoType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhotoType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhotoType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhotoType>() {
              public PhotoType findValueByNumber(int number) {
                return PhotoType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.protobuf.jbean.PersonProto.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhotoType[] VALUES = values();

      public static PhotoType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhotoType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.protobuf.Person.PhotoType)
    }

    public interface PhotoNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.protobuf.Person.PhotoNumber)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string number = 1;</code>
       */
      java.lang.String getNumber();
      /**
       * <code>string number = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      /**
       * <code>.com.protobuf.Person.PhotoType type = 2;</code>
       */
      int getTypeValue();
      /**
       * <code>.com.protobuf.Person.PhotoType type = 2;</code>
       */
      com.protobuf.jbean.PersonProto.Person.PhotoType getType();
    }
    /**
     * Protobuf type {@code com.protobuf.Person.PhotoNumber}
     */
    public  static final class PhotoNumber extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.protobuf.Person.PhotoNumber)
        PhotoNumberOrBuilder {
      // Use PhotoNumber.newBuilder() to construct.
      private PhotoNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PhotoNumber() {
        number_ = "";
        type_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private PhotoNumber(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                number_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.jbean.PersonProto.internal_static_com_protobuf_Person_PhotoNumber_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.jbean.PersonProto.internal_static_com_protobuf_Person_PhotoNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.jbean.PersonProto.Person.PhotoNumber.class, com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder.class);
      }

      public static final int NUMBER_FIELD_NUMBER = 1;
      private volatile java.lang.Object number_;
      /**
       * <code>string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        }
      }
      /**
       * <code>string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>.com.protobuf.Person.PhotoType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.protobuf.Person.PhotoType type = 2;</code>
       */
      public com.protobuf.jbean.PersonProto.Person.PhotoType getType() {
        com.protobuf.jbean.PersonProto.Person.PhotoType result = com.protobuf.jbean.PersonProto.Person.PhotoType.valueOf(type_);
        return result == null ? com.protobuf.jbean.PersonProto.Person.PhotoType.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNumberBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
        }
        if (type_ != com.protobuf.jbean.PersonProto.Person.PhotoType.MOBILE.getNumber()) {
          output.writeEnum(2, type_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNumberBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
        }
        if (type_ != com.protobuf.jbean.PersonProto.Person.PhotoType.MOBILE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.protobuf.jbean.PersonProto.Person.PhotoNumber)) {
          return super.equals(obj);
        }
        com.protobuf.jbean.PersonProto.Person.PhotoNumber other = (com.protobuf.jbean.PersonProto.Person.PhotoNumber) obj;

        boolean result = true;
        result = result && getNumber()
            .equals(other.getNumber());
        result = result && type_ == other.type_;
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.protobuf.jbean.PersonProto.Person.PhotoNumber prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.protobuf.Person.PhotoNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.protobuf.Person.PhotoNumber)
          com.protobuf.jbean.PersonProto.Person.PhotoNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.protobuf.jbean.PersonProto.internal_static_com_protobuf_Person_PhotoNumber_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.protobuf.jbean.PersonProto.internal_static_com_protobuf_Person_PhotoNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.protobuf.jbean.PersonProto.Person.PhotoNumber.class, com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder.class);
        }

        // Construct using com.protobuf.jbean.PersonProto.Person.PhotoNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          number_ = "";

          type_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.protobuf.jbean.PersonProto.internal_static_com_protobuf_Person_PhotoNumber_descriptor;
        }

        public com.protobuf.jbean.PersonProto.Person.PhotoNumber getDefaultInstanceForType() {
          return com.protobuf.jbean.PersonProto.Person.PhotoNumber.getDefaultInstance();
        }

        public com.protobuf.jbean.PersonProto.Person.PhotoNumber build() {
          com.protobuf.jbean.PersonProto.Person.PhotoNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.protobuf.jbean.PersonProto.Person.PhotoNumber buildPartial() {
          com.protobuf.jbean.PersonProto.Person.PhotoNumber result = new com.protobuf.jbean.PersonProto.Person.PhotoNumber(this);
          result.number_ = number_;
          result.type_ = type_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.protobuf.jbean.PersonProto.Person.PhotoNumber) {
            return mergeFrom((com.protobuf.jbean.PersonProto.Person.PhotoNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.protobuf.jbean.PersonProto.Person.PhotoNumber other) {
          if (other == com.protobuf.jbean.PersonProto.Person.PhotoNumber.getDefaultInstance()) return this;
          if (!other.getNumber().isEmpty()) {
            number_ = other.number_;
            onChanged();
          }
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.protobuf.jbean.PersonProto.Person.PhotoNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.protobuf.jbean.PersonProto.Person.PhotoNumber) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object number_ = "";
        /**
         * <code>string number = 1;</code>
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string number = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder clearNumber() {
          
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          number_ = value;
          onChanged();
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.com.protobuf.Person.PhotoType type = 2;</code>
         */
        public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.com.protobuf.Person.PhotoType type = 2;</code>
         */
        public Builder setTypeValue(int value) {
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.com.protobuf.Person.PhotoType type = 2;</code>
         */
        public com.protobuf.jbean.PersonProto.Person.PhotoType getType() {
          com.protobuf.jbean.PersonProto.Person.PhotoType result = com.protobuf.jbean.PersonProto.Person.PhotoType.valueOf(type_);
          return result == null ? com.protobuf.jbean.PersonProto.Person.PhotoType.UNRECOGNIZED : result;
        }
        /**
         * <code>.com.protobuf.Person.PhotoType type = 2;</code>
         */
        public Builder setType(com.protobuf.jbean.PersonProto.Person.PhotoType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.com.protobuf.Person.PhotoType type = 2;</code>
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.protobuf.Person.PhotoNumber)
      }

      // @@protoc_insertion_point(class_scope:com.protobuf.Person.PhotoNumber)
      private static final com.protobuf.jbean.PersonProto.Person.PhotoNumber DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.protobuf.jbean.PersonProto.Person.PhotoNumber();
      }

      public static com.protobuf.jbean.PersonProto.Person.PhotoNumber getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PhotoNumber>
          PARSER = new com.google.protobuf.AbstractParser<PhotoNumber>() {
        public PhotoNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new PhotoNumber(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PhotoNumber> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PhotoNumber> getParserForType() {
        return PARSER;
      }

      public com.protobuf.jbean.PersonProto.Person.PhotoNumber getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 3;
    private volatile java.lang.Object birthday_;
    /**
     * <code>string birthday = 3;</code>
     */
    public java.lang.String getBirthday() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthday_ = s;
        return s;
      }
    }
    /**
     * <code>string birthday = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBirthdayBytes() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthday_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAN_FIELD_NUMBER = 4;
    private boolean man_;
    /**
     * <code>bool man = 4;</code>
     */
    public boolean getMan() {
      return man_;
    }

    public static final int PHONE_FIELD_NUMBER = 5;
    private java.util.List<com.protobuf.jbean.PersonProto.Person.PhotoNumber> phone_;
    /**
     * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
     */
    public java.util.List<com.protobuf.jbean.PersonProto.Person.PhotoNumber> getPhoneList() {
      return phone_;
    }
    /**
     * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
     */
    public java.util.List<? extends com.protobuf.jbean.PersonProto.Person.PhotoNumberOrBuilder> 
        getPhoneOrBuilderList() {
      return phone_;
    }
    /**
     * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
     */
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
     */
    public com.protobuf.jbean.PersonProto.Person.PhotoNumber getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
     */
    public com.protobuf.jbean.PersonProto.Person.PhotoNumberOrBuilder getPhoneOrBuilder(
        int index) {
      return phone_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (!getBirthdayBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, birthday_);
      }
      if (man_ != false) {
        output.writeBool(4, man_);
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeMessage(5, phone_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (!getBirthdayBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, birthday_);
      }
      if (man_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, man_);
      }
      for (int i = 0; i < phone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, phone_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protobuf.jbean.PersonProto.Person)) {
        return super.equals(obj);
      }
      com.protobuf.jbean.PersonProto.Person other = (com.protobuf.jbean.PersonProto.Person) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && getBirthday()
          .equals(other.getBirthday());
      result = result && (getMan()
          == other.getMan());
      result = result && getPhoneList()
          .equals(other.getPhoneList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
      hash = (53 * hash) + getBirthday().hashCode();
      hash = (37 * hash) + MAN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMan());
      if (getPhoneCount() > 0) {
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protobuf.jbean.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.jbean.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.jbean.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.jbean.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.jbean.PersonProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.jbean.PersonProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.jbean.PersonProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protobuf.jbean.PersonProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protobuf.jbean.PersonProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protobuf.jbean.PersonProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protobuf.jbean.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protobuf.jbean.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protobuf.jbean.PersonProto.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protobuf.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protobuf.Person)
        com.protobuf.jbean.PersonProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.jbean.PersonProto.internal_static_com_protobuf_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.jbean.PersonProto.internal_static_com_protobuf_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.jbean.PersonProto.Person.class, com.protobuf.jbean.PersonProto.Person.Builder.class);
      }

      // Construct using com.protobuf.jbean.PersonProto.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPhoneFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        birthday_ = "";

        man_ = false;

        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.jbean.PersonProto.internal_static_com_protobuf_Person_descriptor;
      }

      public com.protobuf.jbean.PersonProto.Person getDefaultInstanceForType() {
        return com.protobuf.jbean.PersonProto.Person.getDefaultInstance();
      }

      public com.protobuf.jbean.PersonProto.Person build() {
        com.protobuf.jbean.PersonProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.jbean.PersonProto.Person buildPartial() {
        com.protobuf.jbean.PersonProto.Person result = new com.protobuf.jbean.PersonProto.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.age_ = age_;
        result.birthday_ = birthday_;
        result.man_ = man_;
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            phone_ = java.util.Collections.unmodifiableList(phone_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.jbean.PersonProto.Person) {
          return mergeFrom((com.protobuf.jbean.PersonProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.jbean.PersonProto.Person other) {
        if (other == com.protobuf.jbean.PersonProto.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getBirthday().isEmpty()) {
          birthday_ = other.birthday_;
          onChanged();
        }
        if (other.getMan() != false) {
          setMan(other.getMan());
        }
        if (phoneBuilder_ == null) {
          if (!other.phone_.isEmpty()) {
            if (phone_.isEmpty()) {
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensurePhoneIsMutable();
              phone_.addAll(other.phone_);
            }
            onChanged();
          }
        } else {
          if (!other.phone_.isEmpty()) {
            if (phoneBuilder_.isEmpty()) {
              phoneBuilder_.dispose();
              phoneBuilder_ = null;
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000010);
              phoneBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhoneFieldBuilder() : null;
            } else {
              phoneBuilder_.addAllMessages(other.phone_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.jbean.PersonProto.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.jbean.PersonProto.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object birthday_ = "";
      /**
       * <code>string birthday = 3;</code>
       */
      public java.lang.String getBirthday() {
        java.lang.Object ref = birthday_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          birthday_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string birthday = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBirthdayBytes() {
        java.lang.Object ref = birthday_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthday_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string birthday = 3;</code>
       */
      public Builder setBirthday(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string birthday = 3;</code>
       */
      public Builder clearBirthday() {
        
        birthday_ = getDefaultInstance().getBirthday();
        onChanged();
        return this;
      }
      /**
       * <code>string birthday = 3;</code>
       */
      public Builder setBirthdayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        birthday_ = value;
        onChanged();
        return this;
      }

      private boolean man_ ;
      /**
       * <code>bool man = 4;</code>
       */
      public boolean getMan() {
        return man_;
      }
      /**
       * <code>bool man = 4;</code>
       */
      public Builder setMan(boolean value) {
        
        man_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool man = 4;</code>
       */
      public Builder clearMan() {
        
        man_ = false;
        onChanged();
        return this;
      }

      private java.util.List<com.protobuf.jbean.PersonProto.Person.PhotoNumber> phone_ =
        java.util.Collections.emptyList();
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          phone_ = new java.util.ArrayList<com.protobuf.jbean.PersonProto.Person.PhotoNumber>(phone_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protobuf.jbean.PersonProto.Person.PhotoNumber, com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder, com.protobuf.jbean.PersonProto.Person.PhotoNumberOrBuilder> phoneBuilder_;

      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public java.util.List<com.protobuf.jbean.PersonProto.Person.PhotoNumber> getPhoneList() {
        if (phoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phone_);
        } else {
          return phoneBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public int getPhoneCount() {
        if (phoneBuilder_ == null) {
          return phone_.size();
        } else {
          return phoneBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public com.protobuf.jbean.PersonProto.Person.PhotoNumber getPhone(int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);
        } else {
          return phoneBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public Builder setPhone(
          int index, com.protobuf.jbean.PersonProto.Person.PhotoNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.set(index, value);
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public Builder setPhone(
          int index, com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public Builder addPhone(com.protobuf.jbean.PersonProto.Person.PhotoNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public Builder addPhone(
          int index, com.protobuf.jbean.PersonProto.Person.PhotoNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(index, value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public Builder addPhone(
          com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public Builder addPhone(
          int index, com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public Builder addAllPhone(
          java.lang.Iterable<? extends com.protobuf.jbean.PersonProto.Person.PhotoNumber> values) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phone_);
          onChanged();
        } else {
          phoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public Builder removePhone(int index) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.remove(index);
          onChanged();
        } else {
          phoneBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder getPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public com.protobuf.jbean.PersonProto.Person.PhotoNumberOrBuilder getPhoneOrBuilder(
          int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);  } else {
          return phoneBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public java.util.List<? extends com.protobuf.jbean.PersonProto.Person.PhotoNumberOrBuilder> 
           getPhoneOrBuilderList() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phone_);
        }
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder addPhoneBuilder() {
        return getPhoneFieldBuilder().addBuilder(
            com.protobuf.jbean.PersonProto.Person.PhotoNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder addPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().addBuilder(
            index, com.protobuf.jbean.PersonProto.Person.PhotoNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protobuf.Person.PhotoNumber phone = 5;</code>
       */
      public java.util.List<com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder> 
           getPhoneBuilderList() {
        return getPhoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protobuf.jbean.PersonProto.Person.PhotoNumber, com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder, com.protobuf.jbean.PersonProto.Person.PhotoNumberOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.protobuf.jbean.PersonProto.Person.PhotoNumber, com.protobuf.jbean.PersonProto.Person.PhotoNumber.Builder, com.protobuf.jbean.PersonProto.Person.PhotoNumberOrBuilder>(
                  phone_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.protobuf.Person)
    }

    // @@protoc_insertion_point(class_scope:com.protobuf.Person)
    private static final com.protobuf.jbean.PersonProto.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protobuf.jbean.PersonProto.Person();
    }

    public static com.protobuf.jbean.PersonProto.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public com.protobuf.jbean.PersonProto.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protobuf_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_Person_PhotoNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protobuf_Person_PhotoNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\014com.protobuf\"\355\001\n\006Person\022" +
      "\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\020\n\010birthday\030\003" +
      " \001(\t\022\013\n\003man\030\004 \001(\010\022/\n\005phone\030\005 \003(\0132 .com.p" +
      "rotobuf.Person.PhotoNumber\032K\n\013PhotoNumbe" +
      "r\022\016\n\006number\030\001 \001(\t\022,\n\004type\030\002 \001(\0162\036.com.pr" +
      "otobuf.Person.PhotoType\"+\n\tPhotoType\022\n\n\006" +
      "MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORD\020\002B!\n\022com.prot" +
      "obuf.jbeanB\013PersonProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protobuf_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protobuf_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protobuf_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Birthday", "Man", "Phone", });
    internal_static_com_protobuf_Person_PhotoNumber_descriptor =
      internal_static_com_protobuf_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_protobuf_Person_PhotoNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protobuf_Person_PhotoNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
